### ISSUE TITLE
Like to work on your project

### ISSUE THREAD

**Issue by damiansan239** [adewolejosh/Anonymous-Messenger#1]
Hello. I like this project you have here and I will like to contribute to it so, how is it deployed?
Gonna make my pull request soon.
Thanks

**Comment by adewolejosh** [comment]
Hi Damian,

Thanks for reaching out, I'm glad you like it. For now this project was deployed on heroku (kubool.herokuapp.com) and it was just meant to be like a very personal messenger- for people close to me to message me only. (My thoughts) If you don't mind, we could scale it up to allow users- allowing anyone to anonymously message, and maybe include a email messaging system. (or we could just start out a whole new project on this, if you don't mind)

Better still I'd love to see what you have in mind. Feel free to make a pull request at anytime.

**Comment by damiansan239** [comment]
Okay, that's fine. Working on it
